console.log(2 + 2);
console.log(2 - 3);
console.log(10 / 2);
console.log(2 * 10);
//console.log(2 ** 10);
console.log(5 % 2);
var num = 2;
console.log(num++);
console.log(num);
console.log(++num);
console.log(num--);
console.log(num);
console.log(--num);
var someNum = 10;
var someOtherNum = -someNum;
console.log(someOtherNum);
var strNum = '100';
console.log(strNum);
var convrtNum = + strNum;
console.log(convrtNum);